
package cliente.banco;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "BankServiceImplService", targetNamespace = "http://Service/", wsdlLocation = "http://localhost:8081/BankSoap?wsdl")
public class BankServiceImplService
    extends Service
{

    private static final URL BANKSERVICEIMPLSERVICE_WSDL_LOCATION;
    private static final WebServiceException BANKSERVICEIMPLSERVICE_EXCEPTION;
    private static final QName BANKSERVICEIMPLSERVICE_QNAME = new QName("http://Service/", "BankServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/BankSoap?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BANKSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        BANKSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public BankServiceImplService() {
        super(__getWsdlLocation(), BANKSERVICEIMPLSERVICE_QNAME);
    }

    public BankServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BANKSERVICEIMPLSERVICE_QNAME, features);
    }

    public BankServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, BANKSERVICEIMPLSERVICE_QNAME);
    }

    public BankServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BANKSERVICEIMPLSERVICE_QNAME, features);
    }

    public BankServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BankServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BankService
     */
    @WebEndpoint(name = "BankServiceImplPort")
    public BankService getBankServiceImplPort() {
        return super.getPort(new QName("http://Service/", "BankServiceImplPort"), BankService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BankService
     */
    @WebEndpoint(name = "BankServiceImplPort")
    public BankService getBankServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Service/", "BankServiceImplPort"), BankService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BANKSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw BANKSERVICEIMPLSERVICE_EXCEPTION;
        }
        return BANKSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
