
package cliente.banco;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BankService", targetNamespace = "http://Service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankService {


    /**
     * 
     * @param amount
     * @param fromId
     * @param toId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "transfer", targetNamespace = "http://Service/", className = "cliente.banco.Transfer")
    @ResponseWrapper(localName = "transferResponse", targetNamespace = "http://Service/", className = "cliente.banco.TransferResponse")
    @Action(input = "http://Service/BankService/transferRequest", output = "http://Service/BankService/transferResponse")
    public String transfer(
        @WebParam(name = "fromId", targetNamespace = "")
        String fromId,
        @WebParam(name = "toId", targetNamespace = "")
        String toId,
        @WebParam(name = "amount", targetNamespace = "")
        double amount);

    /**
     * 
     * @param amount
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "withdraw", targetNamespace = "http://Service/", className = "cliente.banco.Withdraw")
    @ResponseWrapper(localName = "withdrawResponse", targetNamespace = "http://Service/", className = "cliente.banco.WithdrawResponse")
    @Action(input = "http://Service/BankService/withdrawRequest", output = "http://Service/BankService/withdrawResponse")
    public String withdraw(
        @WebParam(name = "id", targetNamespace = "")
        String id,
        @WebParam(name = "amount", targetNamespace = "")
        double amount);

    /**
     * 
     * @param amount
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deposit", targetNamespace = "http://Service/", className = "cliente.banco.Deposit")
    @ResponseWrapper(localName = "depositResponse", targetNamespace = "http://Service/", className = "cliente.banco.DepositResponse")
    @Action(input = "http://Service/BankService/depositRequest", output = "http://Service/BankService/depositResponse")
    public String deposit(
        @WebParam(name = "id", targetNamespace = "")
        String id,
        @WebParam(name = "amount", targetNamespace = "")
        double amount);

    /**
     * 
     * @param id
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBalance", targetNamespace = "http://Service/", className = "cliente.banco.GetBalance")
    @ResponseWrapper(localName = "getBalanceResponse", targetNamespace = "http://Service/", className = "cliente.banco.GetBalanceResponse")
    @Action(input = "http://Service/BankService/getBalanceRequest", output = "http://Service/BankService/getBalanceResponse")
    public double getBalance(
        @WebParam(name = "id", targetNamespace = "")
        String id);

    /**
     * 
     * @param id
     * @param initialBalance
     * @param owner
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createAccount", targetNamespace = "http://Service/", className = "cliente.banco.CreateAccount")
    @ResponseWrapper(localName = "createAccountResponse", targetNamespace = "http://Service/", className = "cliente.banco.CreateAccountResponse")
    @Action(input = "http://Service/BankService/createAccountRequest", output = "http://Service/BankService/createAccountResponse")
    public String createAccount(
        @WebParam(name = "id", targetNamespace = "")
        String id,
        @WebParam(name = "owner", targetNamespace = "")
        String owner,
        @WebParam(name = "initialBalance", targetNamespace = "")
        double initialBalance);

}
